<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="158adxtest"
           tests="4"
           failures="1"
           errors="0"
           skipped="3"
           time="28.460">
  <properties />
            <testcase name="Login" time="8.494" classname="com.uiframe.testcases.CreateAddAdver">
                <failure type="java.lang.AssertionError"
                  message="检查登录是否成功 expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: 检查登录是否成功 expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:513)
  org.testng.Assert.assertTrue(Assert.java:42)
  com.uiframe.testcases.CreateAddAdver.Login(CreateAddAdver.java:43)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
  org.testng.internal.Invoker.retryFailed(Invoker.java:967)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1146)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
  org.testng.TestRunner.privateRun(TestRunner.java:782)
  org.testng.TestRunner.run(TestRunner.java:632)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
  org.testng.SuiteRunner.run(SuiteRunner.java:268)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
  org.testng.TestNG.run(TestNG.java:1064)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
      </failure>

          </testcase>
  
            <testcase name="Login" time="0.0" classname="com.uiframe.testcases.CreateAddAdver">
          <skipped />
    </testcase>
            <testcase name="createAdver" time="0.0" classname="com.uiframe.testcases.CreateAddAdver">
          <skipped />
    </testcase>
            <testcase name="Login" time="0.0" classname="com.uiframe.testcases.CreateAddAdver">
          <skipped />
    </testcase>
  
  
</testsuite>
